#!/usr/bin/env bash
# Runs an infinite loop that ignores SIGTERM, printing "I am invincible!!!" instead

# Use trap to catch the SIGTERM signal (signal 15) and run a command instead of exiting
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
